# Generated by Django 6.0.1 on 2026-02-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('view_any_client', 'Can view any client'), ('change_any_client', 'Can change any client'), ('delete_any_client', 'Can delete any client')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_set_mailing_status', 'Can set mailing status'), ('view_any_mailing', 'Can view any mailing'), ('change_any_mailing', 'Can change any mailing'), ('delete_any_mailing', 'Can delete any mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('view_any_message', 'Can view any message'), ('change_any_message', 'Can change any message'), ('delete_any_message', 'Can delete any message')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
