# Generated by Django 6.0.1 on 2026-02-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_client_options_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='mailings.client', verbose_name='Клиенты рассылки'),
        ),
    ]
